# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2232b72bda139f99f041c326daa8c99f9b40de95b59f02da6f282261933e51303c20c52773b75546be6a9672f4a19dac6e673e5fd7114c3d181d8c43123e8bb

test:
  secret_key_base: 7e27787b701d5a949004423b2f65da2e25b266e0163a2b9f349dac1f32dffaa1ce4d030473ebd5754a87126a8923eb2ec2beed45b5c22d450ea8e8275923bf03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
